// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtBZR5G1baCdrq5aWle_67q0awa_-GA74',
    appId: '1:533683727453:web:1e30e0bc116b03f68871b4',
    messagingSenderId: '533683727453',
    projectId: 'community-disaster-hub',
    authDomain: 'community-disaster-hub.firebaseapp.com',
    storageBucket: 'community-disaster-hub.firebasestorage.app',
    measurementId: 'G-PCRNM8MDL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp2q6AUQwBVymrcrJbaY8lC2kGGcaOVVA',
    appId: '1:533683727453:android:2925f9297461960a8871b4',
    messagingSenderId: '533683727453',
    projectId: 'community-disaster-hub',
    storageBucket: 'community-disaster-hub.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtBZR5G1baCdrq5aWle_67q0awa_-GA74',
    appId: '1:533683727453:web:8b783122f0daa6b18871b4',
    messagingSenderId: '533683727453',
    projectId: 'community-disaster-hub',
    authDomain: 'community-disaster-hub.firebaseapp.com',
    storageBucket: 'community-disaster-hub.firebasestorage.app',
    measurementId: 'G-DR92MQGCKG',
  );
}
